default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 1234

development:
  <<: *default
  database: mock_nequi_development
  username: postgres
  password: 1234

test: &test
  <<: *default
  database: mock_nequi_test
  username: postgres
  password: 1234

production:
