default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: mock_nequi_development
  username: postgres
  password: postgres

test: &test
  <<: *default
  database: mock_nequi_test
  username: postgres
  password: postgres

production:
